/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lec06;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rogerjoseulaterivera
 */
public class clientGraphic extends javax.swing.JFrame {

    /**
     * Creates new form clientGraphic
     */
    public clientGraphic() {
        initComponents();
    }
    
    // Verificar que no hayan campos vacios
    public boolean verificaNombreVacio() {
        //metodo que verifica que el usuario no deje camppos sin rellenar 
        boolean result = false;

        if (ipNumberTxtF.getText().isEmpty() && portNumberTxtF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor llenar el campo");
        } else {
            result = true;
            btn_send.setEnabled(true);
        }

        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_send = new javax.swing.JButton();
        chatTxtArea = new javax.swing.JTextField();
        ipNumberTxtF = new javax.swing.JTextField();
        portNumberTxtF = new javax.swing.JTextField();
        ipUIMessage = new javax.swing.JLabel();
        portUIMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Chat de la caja");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btn_send.setText("Enviar");
        btn_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sendMouseClicked(evt);
            }
        });
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        getContentPane().add(btn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        chatTxtArea.setText("jTextField1");
        getContentPane().add(chatTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 340, 40));

        ipNumberTxtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipNumberTxtFActionPerformed(evt);
            }
        });
        getContentPane().add(ipNumberTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, -1));

        portNumberTxtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portNumberTxtFActionPerformed(evt);
            }
        });
        getContentPane().add(portNumberTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 90, -1));

        ipUIMessage.setText("Conectarse a la ip");
        getContentPane().add(ipUIMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        portUIMessage.setText("Con el puerto");
        getContentPane().add(portUIMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        
        if(verificaNombreVacio()){
            Socket s1 = null;
        
            try {
                s1 = new Socket(ipNumberTxtF.getText(), Integer.parseInt(portNumberTxtF.getText()));
            } catch (IOException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error de conexion al servidor, IP o Puerto no son correctos o bien no esta conectado a una conexion de red");
            }

            DataInputStream dis;
            DataOutputStream dos;

            try{
                dos = new DataOutputStream(s1.getOutputStream());
                dis = new DataInputStream(s1.getInputStream());
                dos.writeUTF(chatTxtArea.getText());
                System.out.println(dis.readUTF());
                dis.close();
                s1.close();
            }catch (IOException ex){
               Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
               System.out.println("Error");
            }
        }
        
    }//GEN-LAST:event_btn_sendActionPerformed

    private void portNumberTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portNumberTxtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portNumberTxtFActionPerformed

    private void ipNumberTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipNumberTxtFActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ipNumberTxtFActionPerformed

    private void btn_sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sendMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btn_sendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientGraphic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JTextField chatTxtArea;
    private javax.swing.JTextField ipNumberTxtF;
    private javax.swing.JLabel ipUIMessage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField portNumberTxtF;
    private javax.swing.JLabel portUIMessage;
    // End of variables declaration//GEN-END:variables
}
