/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lec06;

/**
 *
 * @author rogerjoseulaterivera
 */
public class serverGraphic extends javax.swing.JFrame {

    /**
     * Creates new form clientGraphic
     */
    public serverGraphic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        chatTxtArea = new javax.swing.JTextField();
        portNumberTxtF = new javax.swing.JTextField();
        ipUIMessage = new javax.swing.JLabel();
        portUIMessage = new javax.swing.JLabel();
        jYesOnServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Chat de la caja");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        chatTxtArea.setText("jTextField1");
        getContentPane().add(chatTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 360, 90));

        portNumberTxtF.setText("jTextField1");
        getContentPane().add(portNumberTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        ipUIMessage.setText("Encender servidor");
        getContentPane().add(ipUIMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        portUIMessage.setText("Con el puerto");
        getContentPane().add(portUIMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jYesOnServer.setText("Si");
        jYesOnServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYesOnServerActionPerformed(evt);
            }
        });
        getContentPane().add(jYesOnServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jYesOnServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYesOnServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jYesOnServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serverGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serverGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serverGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serverGraphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serverGraphic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatTxtArea;
    private javax.swing.JLabel ipUIMessage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jYesOnServer;
    private javax.swing.JTextField portNumberTxtF;
    private javax.swing.JLabel portUIMessage;
    // End of variables declaration//GEN-END:variables
}
